import { createElement } from 'lwc';
import T002 from 'c/t002';

describe('c-t002', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-t002', {
            is: T002
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const text = element.shadowRoot.querySelector('p')
        expect(text.textContent).toBe('Hello, World!')
    });
    it('TODO: test case generated by CLI command', () => {
        // Arrange
        const element = createElement('c-t002', {
            is: T002
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const text = element.shadowRoot.querySelector('p')
        expect(text.textContent).not.toBe('Hello, Kenny!')
    });
    it('test input change event value', () => {
        // Arrange
        const element = createElement('c-t002', {
            is: T002
        });

        // Act
        document.body.appendChild(element);

        const inputElement = element.shadowRoot.querySelector('lightning-input')
        inputElement.value='Salesforce'
        inputElement.dispatchEvent(new CustomEvent('change'))
        const text = element.shadowRoot.querySelector('p');
        return Promise.resolve().then(()=>{
            expect(text.textContent).toBe('Hello, Salesforce!')
        })
    });

});